### ISSUE TITLE
Allow to define the sass path

### ISSUE THREAD

**Issue by akkie** [madoushi/sbt-sass#1]
The old [sbt-sass](https://github.com/ShaggyYeti/sbt-sass) plugin doesn't have the ability to define the sass path. On Linux systems it uses the command `which sass` to find the sass executable. On my Arch system this doesn't really work in IntelliJ IDEA if the `sass` executable isn't in the system wide `PATH`. Maybe it doesn't source the `.bashrc` file before executing the `which sass` command from inside the IDE. An other use case is to use `bundler` to manage the GEMs. In this case `sass` must be executed with bundler `bundle exec sass`.

**Comment by jan0sch** [comment]
I'll implement that if I've the whole stuff up and running. Hopefully within the next week(s).

**Comment by akkie** [comment]
This was fast. Thanks!
