### ISSUE TITLE
Make minified output optional

### ISSUE THREAD

**Issue by migo** [madoushi/sbt-sass#10]
As far as I can see, at the moment, the sass compiler is always invoked twice:
- once for generating an unminified css file
- once for generating a minified css file

That means that the compilation time could be cut in half if the minified version would be made optional (or removed completely).

Instead, one could use sbt-css-compress in the asset pipeline for generating the minified version only when the application is packaged for deployment.

**Comment by jan0sch** [comment]
Nice idea. If I ever manage to make the port to sbt 1.0 then this would be a nice addition.

**Comment by migo** [comment]
I could try to make the change myself (maybe including the port to sbt 1.0) and create a pull request.

**Comment by jan0sch** [comment]
There is already an issue (#9) for the migration to sbt 1.0. Feel free to give it a try.
Getting that done would be really awesome.

Beware that some code will have to be rewritten to work with 1.0. I've only given this a short look some time ago.
