### ISSUE TITLE
play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[SassCompilerException: Errno::EISDIR: Is a directory @ io_fread

### ISSUE THREAD

**Issue by ArkadyKarev** [madoushi/sbt-sass#13]
Hello!

I'm trying to use "sbt-sass" % "1.1.0" but getting following error:
`play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[SassCompilerException: Errno::EISDIR: Is a directory @ io_fread - <full path to my Play app>/app/assets/node_modules/bs-recipes/recipes/gulp.ruby.sass
`
Play version is 2.5.18, scala is 2.11.7 and sass is 3.5.6, sbt.version is 0.13.11

Any ideas how to fix this issue very appreciated!

**Comment by jan0sch** [comment]
Could you try with the latest sbt of the 0.13 series (0.13.17)?

**Comment by ArkadyKarev** [comment]
Hey @jan0sch ! Thank you for quick response. I've tried sbt 0.13.17, and unfortunately it has no effect

**Comment by jan0sch** [comment]
I guess it is something related to your sass code. The error message states that you want to include a file which is actually a directory.

**Comment by ArkadyKarev** [comment]
I found one strange thing. I deleted almost all scss files from default 'app/assets/css', and left only 2 simple of them for tests. But when I run the app, it says 
> [info] Sass compiling on 79 source(s)

What is that? And I getting the same error. Is it scss from node modules? And probably issue may be there? Any ideas?..

**Comment by jan0sch** [comment]
Probably... Without knowing your code and project structure I can't say more.
