### ISSUE TITLE
Add more usage details to the readme

### ISSUE THREAD

**Issue by nietaki** [madoushi/sbt-sass#2]
Currently the readme states how to install the sbt-sass plugin within a project. It doesn't however state, how it should be used afterwards, which is important and interesting information for people looking to use the plugin.
#### The information that people like me could find useful:
- Is it compatible with Play Framework? Which versions?
- When does the sass compilation take place? On project build?
- Which sass files within the project will be compiled? Where will the output css files be placed? Is it possible to exclude a sass file from compilation?

I understand the answers most, if not all of these questions could be deduced or tested experimentally, but having it available from the get-go would increase the confidence and potentially save people's time.

**Comment by jan0sch** [comment]
Thanks for pointing that out. I'll add some more information to the readme when I've got some time.
